namespace Flattiverse.Connector.Units
{
    public enum PlayerUnitSystemKind
    {
        Hull,
        Shield,
        Armor,
        Thruster,
        Nozzle,
        Scanner,
        Analyzer,
        CellsEnergy,
        CellsParticles,
        BatteryEnergy,
        BatteryParticles,
        WeaponLauncher,
        WeaponPayloadDamage,
        WeaponPayloadRadius,
        WeaponFactory,
        WeaponStorage,
        WeaponAmmunition,
        CargoIron,
        CargoCarbon,
        CargoSilicon,
        CargoPlatinum,
        CargoGold,
        CargoSpecial,
        ExtractorIron,
        ExtractorCarbon,
        ExtractorSilicon,
        ExtractorPlatinum,
        ExtractorGold
    }
}